services:
  react-web:
    image: archiebryann/react-router-app:latest
    build: .
    container_name: react-web
    command: "npm run start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes: {}
networks:
  app-network:
    external: true
